### ISSUE TITLE
Pipeline fails if there are multiple run of the same name in a project

### ISSUE THREAD

**Issue by sunitj** [FischbachLab/nf-basespace#1]
This happened for the following projects.

```bash
230623_TY-16Sv4_DK9R4
230623_WCB-16Sv4_DK9R4
230623_PurityControls-16Sv4_DK9R4
```

Some of the runs had to be rerun due to an indexing issue and the pipeline kept failing with this error:

```bash
mv: will not overwrite just-created 'fastqs/230620-ECOLI1-E11_S59_L001_R1_001.fastq.gz' with 'mytmp/230620_ECOLI1_E11_L001_ds.ad99711e26d149eab98eb3937ee32f36/230620-ECOLI1-E11_S59_L001_R1_001.fastq.gz'
```

This was being caused by the move command `mv mytmp/*/*.fastq.gz fastqs` the follows the `bs download projects` command. One solution could be to force the move command, but we wouldn't be sure if the newer file is overwriting the old file or the other way around. Another possible solution would be to try something like this:

```bash
#!/bin/bash -x

set -euo pipefail

PROJECT_NAME=$1

bs list datasets \
    --api-server=https://api.basespace.illumina.com \
    --access-token=<BASESPACE_TOKEN> \
    --project-name=${PROJECT_NAME} \
    -f csv \
| cut -f 2 -d ',' \
| tail -n +2 \
| xargs -I@ bs download datasets \
    --api-server=https://api.basespace.illumina.com \
    --access-token=<BASESPACE_TOKEN> \
    -i @ \
    -o fastqs \
    --extension=fastq.gz
```

This downloads one copy per run, I'm guessing it's the latest copy, but I haven't been able to verify in the documentation. Due to this uncertainty, I also added the `--newer-than=4d` flag to `bs list datasets` to make extra sure that we were only getting the latest runs.

**Comment by xmeng** [comment]
C
